import os

TEST_DATA_FOLDER = "test_data"
TEST_DATA_FOLDER_DATASETS = os.path.join(TEST_DATA_FOLDER, "datasets")
TEST_DATA_FOLDER_DATASETS_TEST = os.path.join(TEST_DATA_FOLDER_DATASETS, "test")
TEST_DATA_FOLDER_DATASETS_TEST2 = os.path.join(TEST_DATA_FOLDER_DATASETS, "test2")
TEST_DATA_FOLDER_DATASETS_TEST_TIME = os.path.join(
    TEST_DATA_FOLDER_DATASETS, "test_time"
)
TEST_DATA_FOLDER_DATASETS_BATTLEDIM = os.path.join(
    TEST_DATA_FOLDER_DATASETS, "battledim"
)
TEST_DATA_FOLDER_DATASETS_GENERATED = os.path.join(
    TEST_DATA_FOLDER_DATASETS, "generated"
)
